'use client';
import {useEffect,useMemo,useState} from 'react';
import {Bell,Bookmark,HelpCircle,ShieldCheck,CloudSun,X} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {displayValue,displayUnit,thresholdNotices,type Place,type Preferences,type Region,type Notice} from '@/lib/explorer';
import {VARIABLES,type Variable} from '@/lib/forecast';
import type {PublicProduct} from '@/lib/public-data';
import states from '@/public/data/state-index.json';
const regions=states as Region[];
const utc=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:'UTC'})+' UTC';
type Props={data:PublicProduct|null;domain:'india'|'world';source:string;location:Place;region:Region|null;onRegion:(r:Region|null)=>void;onLocation:(p:Place)=>void;onInspect:(n:Notice)=>void;prefs:Preferences;update:(fn:(p:Preferences)=>Preferences)=>void;ready:boolean;storageError:boolean};
export default function ExplorerTools(p:Props){
 const[panel,setPanel]=useState<'alerts'|'safety'|'context'|null>(null),[query,setQuery]=useState(''),[guide,setGuide]=useState(false),[online,setOnline]=useState(true),[showDismissed,setShowDismissed]=useState(false);
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync);};},[]);
 const all=useMemo(()=>p.data&&p.domain==='india'?thresholdNotices(p.data,p.location,p.source):[],[p.data,p.domain,p.location,p.source]);
 const notices=all.filter(n=>showDismissed||!p.prefs.dismissed.includes(n.id));
 const count=all.filter(n=>!p.prefs.dismissed.includes(n.id)).length;
 const saved=p.prefs.favorites.some(x=>x.lat===p.location.lat&&x.lng===p.location.lng);
 const closeGuide=()=>{setGuide(false);p.update(x=>({...x,guideSeen:true}));};
 const toggleSaved=()=>p.update(x=>({...x,favorites:saved?x.favorites.filter(a=>a.lat!==p.location.lat||a.lng!==p.location.lng):[...x.favorites,p.location].slice(-20)}));
 return <>
 <div className="explorer-toolbar">
 {p.domain==='india'&&<div className="state-picker"><label htmlFor="state-search">State / territory</label><input id="state-search" type="search" placeholder="Filter states…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Select state or territory" value={p.region?.name||''} onChange={e=>{const r=regions.find(r=>r.name===e.target.value)||null;p.onRegion(r);setQuery('');}}><option value="">All India</option>{regions.filter(r=>r.name===p.region?.name||r.name.toLowerCase().includes(query.toLowerCase())).map(r=><option key={r.name}>{r.name}</option>)}</select></div>}
 <button className="real-action" onClick={toggleSaved} disabled={!p.ready} aria-pressed={saved}><Bookmark size={15}/>{saved?'Saved':'Save point'}</button>
 <select aria-label="Saved locations" value="" onChange={e=>{const place=p.prefs.favorites[Number(e.target.value)];if(place)p.onLocation(place);}}><option value="" disabled>Saved locations ({p.prefs.favorites.length})</option>{p.prefs.favorites.map((s,i)=><option key={i} value={i}>{s.name} · {s.lat.toFixed(1)}, {s.lng.toFixed(1)}</option>)}</select>
 <select aria-label="Display units" value={p.prefs.units} onChange={e=>p.update(x=>({...x,units:e.target.value as Preferences['units']}))}><option value="metric">Metric units</option><option value="imperial">Imperial units</option></select>
 <button className="real-action" onClick={()=>setPanel('alerts')}><Bell size={15}/>Thresholds{count>0&&<span className="notice-count">{count}</span>}</button>
 <button className="real-action" onClick={()=>setPanel('safety')}><ShieldCheck size={15}/>Safety resources</button>
 <button className="real-action" onClick={()=>setPanel('context')}><CloudSun size={15}/>Point weather</button>
 <button className="real-action" aria-label="Open explorer guide" onClick={()=>setGuide(true)}><HelpCircle size={16}/>Guide</button>
 </div>
 {p.ready&&!p.prefs.guideSeen&&<section className="explorer-intro"><div><strong>Explore a forecast in three steps</strong><p>Select a point or state, choose a source and layer, then drag the timeline. Thresholds describe model output; official warnings are linked in Safety resources.</p></div><button className="real-action" onClick={closeGuide}>Got it</button></section>}
 {(!online||p.data?.from_cache)&&<div className="explorer-status" role="status">{!online?'Offline':'Provider connection unavailable'} · {p.data?`Showing ${p.data.from_cache?'locally cached':'loaded'} run ${p.data.run_id}, retrieved ${utc(p.data.retrieved_at)}. Values may be stale.`:'No saved grid is available.'} Offline reopening requires the app itself to be loaded.</div>}
 {p.storageError&&<p className="explorer-status">Browser storage unavailable. Preferences will last for this session only.</p>}
 <Sheet open={panel!==null} onOpenChange={open=>{if(!open)setPanel(null);}}><SheetContent className="explorer-sheet"><SheetHeader><SheetTitle>{panel==='alerts'?'Forecast thresholds':panel==='safety'?'Safety resources':'Point weather context'}</SheetTitle><SheetDescription>{panel==='alerts'?'Selected grid point · model-derived notices, not official warnings':panel==='safety'?'Official information and emergency contacts':'Open-Meteo · independent of the selected forecast run'}</SheetDescription></SheetHeader>
 <div className="explorer-sheet-body">
 {panel==='alerts'&&<><h3>{p.location.name}</h3><p>Screening thresholds: rainfall ≥64.5 mm / 24h, temperature ≥40°C, or 10 m wind ≥15 m/s. “Elevated” starts at 115.6 mm, 45°C or 20 m/s. These rules do not diagnose floods, heatwaves or cyclones.</p><a href="https://mausam.imd.gov.in/" target="_blank" rel="noreferrer">Check official IMD warnings ↗</a><label className="explorer-check"><input type="checkbox" checked={showDismissed} onChange={e=>setShowDismissed(e.target.checked)}/>Show dismissed ({all.length-count})</label>{p.domain==='world'?<p>Threshold screening is disabled for historical WeatherBench cases.</p>:!p.data?<p>Load a forecast to calculate notices.</p>:<><p>Run: {p.data.run_id} · {p.source}. Missing values are excluded; no notices does not mean conditions are safe.</p>{!notices.length&&<p>No undismissed threshold crossings at this point.</p>}{notices.map(n=><article className={'threshold-card '+n.level.toLowerCase()} key={n.id}><div className="threshold-heading"><strong>{VARIABLES[n.variable].label} · +{n.lead}h</strong><span>{n.level}</span></div><h3>{displayValue(n.value,n.variable,p.prefs.units).toFixed(1)} {displayUnit(n.variable,p.prefs.units)}</h3><p>{n.variable==='rain'?`${utc(n.start)} to `:''}{utc(n.valid)}{Date.parse(n.valid)<Date.now()?' · Past valid time':''}</p><p>{n.source} · grid {n.grid.lat.toFixed(2)}, {n.grid.lng.toFixed(2)} · deterministic value, not a probability.</p><details><summary>Evidence</summary><p>Crosses the application screening threshold of {displayValue(n.threshold,n.variable,p.prefs.units).toFixed(1)} {displayUnit(n.variable,p.prefs.units)}. Initialization: {utc(p.data!.initialization)}. The location is a nearest grid sample, not an area-wide warning.</p></details><div className="explorer-actions"><button className="real-action" onClick={()=>{p.onInspect(n);setPanel(null);}}>Inspect on map</button><button className="real-action" onClick={()=>p.update(x=>({...x,dismissed:x.dismissed.includes(n.id)?x.dismissed.filter(id=>id!==n.id):[...x.dismissed,n.id].slice(-200)}))}>{p.prefs.dismissed.includes(n.id)?'Restore':'Dismiss'}</button></div></article>)}</>}</>}
 {panel==='safety'&&<><article className="resource-card"><h3>Emergency assistance in India</h3><p>112 connects emergency requests for police, fire and rescue, and health services in India.</p><a className="emergency-link" href="tel:112">Call 112</a><a href="https://112.gov.in/" target="_blank" rel="noreferrer">Government ERSS information ↗</a><small>Outside India, use the local emergency number.</small></article><article className="resource-card"><h3>Weather warnings</h3><p>Consult IMD for district warnings, nowcasts and cyclone bulletins. Follow instructions from local authorities.</p><a href="https://mausam.imd.gov.in/" target="_blank" rel="noreferrer">India Meteorological Department ↗</a></article><article className="resource-card"><h3>Disaster preparedness</h3><p>Use the National Disaster Management Authority’s official guidance to prepare for floods, heat and other hazards.</p><a href="https://ndma.gov.in/" target="_blank" rel="noreferrer">NDMA guidance ↗</a></article><p>Reference links checked 26 September 2026. Links need connectivity; the emergency number and this resource summary remain visible while this app is open. No nearby facility locations or official alert feed are loaded here.</p></>}
 {panel==='context'&&<PointContext place={p.location} units={p.prefs.units}/>}
 </div></SheetContent></Sheet>
 <Dialog open={guide} onOpenChange={setGuide}><DialogContent className="real-dialog"><DialogHeader><DialogTitle>Explore MausamSetu</DialogTitle><DialogDescription>Forecasts, evidence and your saved places</DialogDescription></DialogHeader><ol className="explorer-guide"><li><strong>Choose a location.</strong> Click the map, select a city, or navigate to a state. State selection zooms to its boundary and chooses a representative point, not a statewide average.</li><li><strong>Compare sources.</strong> Select GFS, GEFS ensemble mean, IFS, AIFS, or the equal baseline when available. Colours represent the selected variable; wind particles show direction.</li><li><strong>Move through time.</strong> Drag the timeline. Rainfall is a rolling 24-hour total. Other layers are instantaneous fields.</li><li><strong>Inspect evidence.</strong> Threshold notices include source, grid position and valid time. These are screening rules, not official warnings or calibrated probabilities.</li><li><strong>Make it yours.</strong> Save up to 20 points and select display units. Exports retain original scientific units. A verified grid is cached locally after a successful load, when browser storage permits.</li><li><strong>Check point context.</strong> Open-Meteo uses its own current model data and timestamp. It does not alter the blend or WeatherBench scores.</li></ol><button className="real-action" onClick={closeGuide}>Got it</button></DialogContent></Dialog>
 </>;
}
type PointData={time:string;retrieved_at:string;interval_seconds:number;temperature:number|null;humidity:number|null;wind:number|null;precipitation:number|null;grid:{lat:number;lng:number};model_selection:string};
function PointContext({place,units}:{place:Place;units:Preferences['units']}){
 const[data,setData]=useState<PointData|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const ctl=new AbortController();setData(null);setError('');fetch(`/api/point-weather?lat=${place.lat}&lng=${place.lng}`,{signal:ctl.signal}).then(async r=>{const d=await r.json() as PointData & {error?:string};if(!r.ok)throw Error(d.error||'Point weather unavailable');setData(d);}).catch(e=>{if(!ctl.signal.aborted)setError(e.message);});return()=>ctl.abort();},[place.lat,place.lng,retry]);
 const formatted=(v:number|null,variable:Variable)=>v===null?'Unavailable':displayValue(v,variable,units).toFixed(1)+' '+displayUnit(variable,units);
 return <><h3>{place.name}</h3><p>Modelled current conditions from Open-Meteo’s Best Match. These are not station observations and are independent of the map’s selected run and lead.</p>{error?<div role="alert"><p>{error}</p><button className="real-action" onClick={()=>setRetry(x=>x+1)}>Retry point weather</button></div>:!data?<p role="status">Loading point weather…</p>:<article className="resource-card"><p>Valid {utc(data.time)}</p><dl className="point-metrics"><dt>Temperature</dt><dd>{formatted(data.temperature,'temperature')}</dd><dt>Relative humidity</dt><dd>{data.humidity===null?'Unavailable':data.humidity+'%'}</dd><dt>10 m wind</dt><dd>{formatted(data.wind,'wind')}</dd><dt>Precipitation / {data.interval_seconds/60} min</dt><dd>{formatted(data.precipitation,'rain')}</dd></dl><p>Grid {data.grid.lat.toFixed(2)}, {data.grid.lng.toFixed(2)} · {data.model_selection}</p><small>Retrieved {utc(data.retrieved_at)} · refresh cache: 10 minutes</small></article>}<a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather data by Open-Meteo.com ↗</a><p><a href="https://open-meteo.com/en/terms" target="_blank" rel="noreferrer">Provider terms</a> · Free endpoint for noncommercial use. A commercial deployment needs the appropriate provider service.</p></>;
}
