'use client';
import { useEffect, useRef, useState } from 'react';
import * as maplibregl from 'maplibre-gl';
import { Map as LibreMap, Marker } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { SOURCES,COLORS,VARIABLES,forecast,truth,getWeights,modelValues,windVector,LOCATIONS, type Layer,type Variable,type Location,color } from '@/lib/forecast';
import { Plus,Minus,LocateFixed } from 'lucide-react';
export type Camera={center:[number,number],zoom:number};
type Props={variable:Variable;layer:Layer;lead:number;location:Location;onPick:(lat:number,lng:number)=>void;weightSource?:string;threshold?:number;opacity?:number;particles?:boolean;camera?:Camera;onCamera?:(c:Camera)=>void;compact?:boolean;borders?:boolean};
export default function WeatherMap(props:Props){
 const host=useRef<HTMLDivElement>(null),map=useRef<LibreMap|null>(null),marker=useRef<Marker|null>(null),raster=useRef<HTMLCanvasElement|null>(null),wind=useRef<HTMLCanvasElement>(null),latest=useRef(props);latest.current=props;const[ready,setReady]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{if(!host.current)return;maplibregl.setWorkerUrl('/maplibre/maplibre-gl-worker.mjs');let m:LibreMap;try{m=new maplibregl.Map({container:host.current,center:props.camera?.center||[80.5,22],zoom:props.camera?.zoom||3.8,minZoom:2,maxZoom:9,attributionControl:false,style:{version:8,sources:{land:{type:'geojson',data:'/data/countries.geojson'}},layers:[{id:'sea',type:'background',paint:{'background-color':'#0b1825'}},{id:'land',type:'fill',source:'land',paint:{'fill-color':'#182b39'}},{id:'borders',type:'line',source:'land',paint:{'line-color':'#7b8b97','line-opacity':.42,'line-width':.7}}]}});map.current=m;}catch{setError('Interactive map unavailable. Use location search to inspect forecasts.');return;}
 m.addControl(new maplibregl.AttributionControl({compact:true,customAttribution:'Natural Earth · <a href="https://www.geoboundaries.org" target="_blank">geoBoundaries</a> / DataMeet (CC BY 2.5 IN) · illustrative'}),'bottom-left');
 m.on('load',()=>{if(!latest.current.camera)m.fitBounds([[66,6],[99,37]],{padding:{top:85,bottom:110,left:25,right:25},duration:0});const c=document.createElement('canvas');c.width=220;c.height=220;raster.current=c;m.addSource('weather',{type:'canvas',canvas:c,coordinates:[[65,38],[100,38],[100,5],[65,5]],animate:false});m.addSource('states',{type:'geojson',data:'/data/india-states.geojson'});m.addLayer({id:'states',type:'line',source:'states',paint:{'line-color':'#b4d0d8','line-opacity':.22,'line-width':.65}});m.addLayer({id:'weather',type:'raster',source:'weather',paint:{'raster-opacity':.78,'raster-fade-duration':400}},'borders');
 LOCATIONS.forEach(l=>{const el=document.createElement('button');el.className='city-label';el.textContent=l.name;el.setAttribute('aria-label','Inspect '+l.name);el.onclick=e=>{e.stopPropagation();latest.current.onPick(l.lat,l.lng);};new Marker({element:el}).setLngLat([l.lng,l.lat]).addTo(m);});
 const el=document.createElement('div');el.className='selected-marker';marker.current=new Marker({element:el}).setLngLat([latest.current.location.lng,latest.current.location.lat]).addTo(m);setReady(true);});
 m.on('click',e=>{if(e.lngLat.lat>=5&&e.lngLat.lat<=38&&e.lngLat.lng>=65&&e.lngLat.lng<=100)latest.current.onPick(e.lngLat.lat,e.lngLat.lng);});m.on('move',()=>{if(m.isMoving()&&latest.current.onCamera){const c=m.getCenter();latest.current.onCamera({center:[c.lng,c.lat],zoom:m.getZoom()});}});
 const resize=new ResizeObserver(()=>m.resize());resize.observe(host.current);return()=>{resize.disconnect();m.remove();map.current=null;};
 },[]);
 useEffect(()=>{if(!ready||!map.current||!props.camera)return;const c=map.current.getCenter();if(Math.abs(c.lng-props.camera.center[0])>.00001||Math.abs(c.lat-props.camera.center[1])>.00001||Math.abs(map.current.getZoom()-props.camera.zoom)>.001)map.current.jumpTo(props.camera);},[props.camera,ready]);
 useEffect(()=>{if(ready&&map.current?.getLayer('states'))map.current.setLayoutProperty('states','visibility',props.borders===false?'none':'visible');},[props.borders,ready]);
 useEffect(()=>{marker.current?.setLngLat([props.location.lng,props.location.lat]);},[props.location,ready]);
 useEffect(()=>{if(!ready||!raster.current||!map.current)return;const c=raster.current,ctx=c.getContext('2d')!,img=ctx.createImageData(c.width,c.height);const {variable:v,layer,lead}=props;const merc=(lat:number)=>Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));const top=merc(38),bottom=merc(5);
 for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const lng=65+x/(c.width-1)*35,lat=(2*Math.atan(Math.exp(top+(bottom-top)*y/(c.height-1)))-Math.PI/2)*180/Math.PI;const weights=getWeights(lat,lng,lead,v),values=modelValues(lat,lng,lead,v);let value=values.reduce((a,b,i)=>a+b*weights[i],0),min=v==='temperature'?5:v==='pressure'?985:0,max=VARIABLES[v].max,colors=VARIABLES[v].colors;let rgb:number[];
 if(layer==='dominant'){const s=COLORS[SOURCES[weights.indexOf(Math.max(...weights))]];rgb=[1,3,5].map(k=>parseInt(s.slice(k,k+2),16));}
 else {if(SOURCES.includes(layer as typeof SOURCES[number]))value=values[SOURCES.indexOf(layer as typeof SOURCES[number])];if(layer==='weights'){value=weights[SOURCES.indexOf((props.weightSource||'NEPS') as typeof SOURCES[number])]*100;max=100;min=0;colors=['#10232c','#27778b','#5adaca'];}
 if(['risk','uncertainty','agreement'].includes(layer)){const f=forecast(lat,lng,lead,v,props.threshold);value=layer==='risk'?f.probability*100:layer==='agreement'?f.agreement:f.p90-f.p10;min=0;max=layer==='uncertainty'?(v==='rain'?100:15):100;colors=layer==='agreement'?['#df9a61','#577b99','#66d4c4']:['#16334a','#536bc4','#ae7cbe','#eea07a'];}rgb=color(value,colors,min,max);}
 const k=(y*c.width+x)*4;img.data[k]=rgb[0];img.data[k+1]=rgb[1];img.data[k+2]=rgb[2];img.data[k+3]=layer==='dominant'?175:Math.round(v==='rain'&&['blend',...SOURCES].includes(layer)?Math.min(200,50+value*3):190);}
 ctx.putImageData(img,0,0);(map.current.getSource('weather') as maplibregl.CanvasSource).play();map.current.triggerRepaint();requestAnimationFrame(()=>{(map.current?.getSource('weather') as maplibregl.CanvasSource)?.pause();});map.current.setPaintProperty('weather','raster-opacity',props.opacity??.8);
 },[props.variable,props.layer,props.lead,props.threshold,props.weightSource,props.opacity,ready]);
 useEffect(()=>{if(!ready||!wind.current||!map.current)return;const canvas=wind.current,ctx=canvas.getContext('2d')!;if(!props.particles||matchMedia('(prefers-reduced-motion: reduce)').matches){ctx.clearRect(0,0,canvas.width,canvas.height);return;}let raf=0;let previous=0;const points=Array.from({length:props.compact?120:450},()=>({lng:65+Math.random()*35,lat:5+Math.random()*33,age:Math.random()*120}));const animate=(now:number)=>{raf=requestAnimationFrame(animate);if(now-previous<33)return;previous=now;const m=map.current;if(!m)return;const w=m.getCanvas().clientWidth,h=m.getCanvas().clientHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.globalCompositeOperation='destination-in';ctx.fillStyle='rgba(0,0,0,.88)';ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over';ctx.strokeStyle='rgba(209,241,248,.50)';ctx.lineWidth=.8;points.forEach(p=>{const a=m.project([p.lng,p.lat]);const v=windVector(p.lat,p.lng,latest.current.lead);p.lng+=v.u*.002;p.lat+=v.v*.002;const b=m.project([p.lng,p.lat]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();if(p.age++>120||b.x<0||b.x>w||b.y<0||b.y>h){const ll=m.unproject([Math.random()*w,Math.random()*h]);p.lng=ll.lng;p.lat=ll.lat;p.age=0;}});};raf=requestAnimationFrame(animate);return()=>{cancelAnimationFrame(raf);ctx.clearRect(0,0,canvas.width,canvas.height);};},[ready,props.particles,props.compact]);
 return <div className="weather-map"><div ref={host} className="map-host" aria-label="Interactive forecast map of India"/><canvas ref={wind} className="wind-canvas" aria-hidden="true"/>{error&&<div className="map-error">{error}</div>}<div className="map-controls"><button title="Zoom in" aria-label="Zoom in" onClick={()=>map.current?.zoomIn()}><Plus size={17}/></button><button title="Zoom out" aria-label="Zoom out" onClick={()=>map.current?.zoomOut()}><Minus size={17}/></button><button title="Reset India view" aria-label="Reset India view" onClick={()=>map.current?.fitBounds([[66,6],[99,37]],{padding:props.compact?15:{top:85,bottom:110,left:25,right:25},duration:600})}><LocateFixed size={17}/></button></div></div>;
}
