'use client';
import RealWorkspace from '@/components/mausam/real-workspace';
import {useCallback,useEffect,useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import {CloudRain,Wind,Thermometer,Layers,Activity,Play,Pause,MapPin,ChevronRight,Waypoints,Search,Download,Info,Shield,BarChart3,SlidersHorizontal,Compass,Eye,Maximize,Clock,ArrowUpRight,X} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {SidebarProvider,Sidebar,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {Button} from '@/components/ui/button';
import {Tooltip,TooltipTrigger,TooltipContent,TooltipProvider} from '@/components/ui/tooltip';
import {forecast,VARIABLES,LOCATIONS,SOURCES,COLORS,nearest,period,INIT,RUN,type Variable,type Layer,type Source,type Location} from '@/lib/forecast';
import {type Case} from '@/lib/verification';
import {Compare,Extremes,Verification,Replay,Operations} from '@/components/mausam/workspaces';
import {Picker,downloadFile} from '@/components/mausam/controls';
const WeatherMap=dynamic(()=>import('@/components/mausam/weather-map'),{ssr:false});
const Chart=dynamic(()=>import('@/components/mausam/chart'),{ssr:false});
type Workspace='forecast'|'compare'|'extremes'|'verification'|'replay'|'operations';
const NAV:Workspace[]=['forecast','compare','extremes','verification','replay','operations'];
const LAYERS:{id:Layer;label:string;icon:typeof Layers}[]=[{id:'blend',label:'Blended forecast',icon:Layers},{id:'risk',label:'Extreme risk',icon:Shield},{id:'uncertainty',label:'Uncertainty',icon:Activity},{id:'agreement',label:'Model agreement',icon:Waypoints},{id:'dominant',label:'Dominant model',icon:Compass},{id:'weights',label:'Source weights',icon:BarChart3}];
const gridAxis={axisLine:{lineStyle:{color:'#304251'}},axisTick:{show:false},axisLabel:{color:'#8da5b8',fontSize:10},splitLine:{lineStyle:{color:'#233342'}}};
function IconButton({label,children,onClick}:{label:string;children:React.ReactNode;onClick:()=>void}){return <Tooltip><TooltipTrigger asChild><button className="icon-button" aria-label={label} onClick={onClick}>{children}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;}
export default function Home(){const[demo,setDemo]=useState(false);return demo?<><button className="back-to-real" onClick={()=>setDemo(false)}>← Real data</button><DemoHome/></>:<RealWorkspace onDemo={()=>setDemo(true)}/>;}
function DemoHome(){
 const[tab,setTab]=useState<Workspace>('forecast'),[variable,setVariable]=useState<Variable>('rain'),[layer,setLayer]=useState<Layer>('blend'),[lead,setLead]=useState(72),[loc,setLoc]=useState(LOCATIONS[0]),[playing,setPlaying]=useState(false),[tz,setTz]=useState('UTC'),[threshold,setThreshold]=useState(64.5),[opacity,setOpacity]=useState(.8),[particles,setParticles]=useState(true),[borders,setBorders]=useState(true),[weightSource,setWeightSource]=useState<Source>('NEPS'),[explain,setExplain]=useState(false),[info,setInfo]=useState(false),[mobilePanel,setMobilePanel]=useState(false),[mobileLayers,setMobileLayers]=useState(false),[rows,setRows]=useState<Case[]>([]),[loading,setLoading]=useState(true),[dataError,setDataError]=useState('');
 const f=useMemo(()=>forecast(loc.lat,loc.lng,lead,variable,threshold),[loc,lead,variable,threshold]);const valid=period(lead,variable,tz);const config=VARIABLES[variable];
 const changeVariable=(v:Variable)=>{setVariable(v);setThreshold(VARIABLES[v].threshold);};
 const pick=useCallback((lat:number,lng:number)=>{setLoc(nearest(lat,lng));},[]);
 const fetchRows=useCallback(async()=>{setLoading(true);setDataError('');try{const r=await fetch('/data/verification.json');if(!r.ok)throw Error('The verification dataset could not be loaded.');const d=await r.json() as {rows:Case[]};setRows(d.rows);}catch(e){setDataError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{fetchRows();},[fetchRows]);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setLead(h=>h>=168?24:h+6),1000);return()=>clearInterval(id);},[playing]);
 useEffect(()=>{if(['verification','operations','replay'].includes(tab))setPlaying(false);},[tab]);
 const exportPoint=()=>downloadFile(`mausamsetu-${loc.name.replaceAll(' ','-')}-${lead}h.json`,JSON.stringify({run_id:RUN,data_kind:'synthetic',location:loc,variable,lead,units:config.unit,valid,threshold,...f},null,2));
 const exportSeries=()=>{const text='run_id,data_kind,latitude,longitude,variable,lead_hours,valid_start,valid_end,units,mean,p10,p90,probability\n'+Array.from({length:25},(_,i)=>24+i*6).map(h=>{const r=forecast(loc.lat,loc.lng,h,variable,threshold),p=period(h,variable);return [RUN,'synthetic',loc.lat,loc.lng,variable,h,p.start,p.end,config.unit,r.mean,r.p10,r.p90,r.probability].join(',');}).join('\n');downloadFile('mausamsetu-forecast-series.csv',text,'text/csv');};
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tool={name:'inspect_mausamsetu_forecast',title:'Inspect a MausamSetu forecast',description:'Select a location, variable and lead time in the visible forecast workspace. Returns explicitly synthetic forecast values.',inputSchema:{type:'object',properties:{latitude:{type:'number',minimum:5,maximum:38},longitude:{type:'number',minimum:65,maximum:100},lead_hours:{type:'integer',minimum:24,maximum:168,multipleOf:6},variable:{type:'string',enum:['rain','temperature','wind','pressure']}},required:['latitude','longitude','lead_hours','variable'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const p=input as {latitude:number;longitude:number;lead_hours:number;variable:Variable};if(!p||typeof p.latitude!=='number'||typeof p.longitude!=='number'||![p.latitude,p.longitude,p.lead_hours].every(Number.isFinite)||p.latitude<5||p.latitude>38||p.longitude<65||p.longitude>100||p.lead_hours<24||p.lead_hours>168||p.lead_hours%6!==0||!Object.hasOwn(VARIABLES,p.variable))throw new Error('Invalid forecast selection');setLoc(nearest(p.latitude,p.longitude));setVariable(p.variable);setThreshold(VARIABLES[p.variable].threshold);setLead(p.lead_hours);setTab('forecast');setPlaying(false);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {run_id:RUN,data_kind:'synthetic',...forecast(p.latitude,p.longitude,p.lead_hours,p.variable)};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const openEvent=(l:Location,v:Variable,target:Workspace)=>{setLoc(l);changeVariable(v);setLayer('risk');setTab(target);};
 const layersContent=<><div className="eyebrow">WORKSPACE</div><h2>Forecast explorer</h2><div className="eyebrow section-label">WEATHER</div><SidebarMenu>{(['rain','temperature','wind','pressure'] as Variable[]).map((v,i)=>{const I=[CloudRain,Thermometer,Wind,Activity][i];return <SidebarMenuItem key={v}><SidebarMenuButton className={'layer-button '+(v===variable?'active':'')} isActive={v===variable} onClick={()=>changeVariable(v)}><I size={17}/><span>{VARIABLES[v].label}</span></SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu><div className="eyebrow section-label">MAUSAMSETU AI</div><SidebarMenu>{LAYERS.map(({id,label,icon:I})=><SidebarMenuItem key={id}><SidebarMenuButton className={'layer-button '+(id===layer?'active':'')} isActive={id===layer} onClick={()=>setLayer(id)}><I size={16}/><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>{layer==='weights'&&<Picker label="Source weight map" value={weightSource} onChange={s=>setWeightSource(s as Source)} options={SOURCES.map(s=>({value:s,label:s+' contribution'}))}/>}<div className="eyebrow section-label">MODEL SOURCES</div><div className="source-buttons">{SOURCES.map(s=><button key={s} className={layer===s?'active':''} onClick={()=>setLayer(s)}><i style={{background:COLORS[s]}}/>{s}</button>)}</div><div className="map-settings"><div className="setting-row"><label htmlFor="particles">Wind particles</label><Switch id="particles" checked={particles} onCheckedChange={setParticles}/></div><div className="setting-row"><label htmlFor="borders">State boundaries</label><Switch id="borders" checked={borders} onCheckedChange={setBorders}/></div><div className="setting-row"><span>Layer opacity</span><span>{Math.round(opacity*100)}%</span></div><Slider aria-label="Layer opacity" value={[opacity*100]} min={10} max={100} step={5} onValueChange={x=>setOpacity(x[0]/100)}/></div><div className="panel-foot"><Shield size={12}/> Experimental guidance<br/>Synthetic demonstration run</div></>;
 const detail=<><div className="location-top"><div className="eyebrow"><MapPin size={13}/> SELECTED LOCATION</div><IconButton label="Export point forecast" onClick={exportPoint}><Download size={15}/></IconButton></div><h2>{loc.name}</h2><p>{loc.state} · {loc.lat.toFixed(2)}°N, {loc.lng.toFixed(2)}°E</p><div className="valid-period"><Clock size={12}/>{valid.label}</div><div className="divider"/><div className="eyebrow">BLENDED {config.label.toUpperCase()}</div><div className="forecast-number">{f.mean.toFixed(1)} <span>{config.unit}</span></div><span className="number-caption">Predictive mean · {variable==='rain'?'24-hour total':variable==='wind'?'10 m wind speed':variable==='temperature'?'2 m temperature':'mean sea level'}</span><div className="metric-row"><span>P10–P90 interval</span><strong>{f.p10.toFixed(1)}–{f.p90.toFixed(1)} {config.unit}</strong></div><div className="interval-bar"/><div className="risk-card"><div><span>Probability of exceeding</span><Picker label="Extreme probability threshold" value={String(threshold)} onChange={s=>setThreshold(Number(s))} options={(variable==='rain'?[10,35.5,64.5,115.6,204.5]:variable==='temperature'?[35,40,45]:variable==='wind'?[10,17,25]:[1000,1010,1020]).map(n=>({value:String(n),label:n+' '+config.unit}))}/></div><strong>{Math.round(f.probability*100)}<small>%</small></strong></div><div className="divider"/><div className="eyebrow">MODEL CONTRIBUTIONS<Tooltip><TooltipTrigger asChild><button aria-label="About model weights"><Info size={12}/></button></TooltipTrigger><TooltipContent>Contribution to the mixture, not probability of being correct.</TooltipContent></Tooltip></div><div className="weights">{SOURCES.map((s,i)=><div className="weight-row" key={s}><div><button onClick={()=>{setWeightSource(s);setLayer('weights');}}><i style={{background:COLORS[s]}}/>{s}</button><b>{(f.weights[i]*100).toFixed(1)}%</b></div><div className="weight-track"><div style={{background:COLORS[s],width:f.weights[i]*100+'%'}}/></div></div>)}</div><button className="explain-button" onClick={()=>setExplain(true)}>Explain this blend<ChevronRight size={17}/></button><div className="agreement-row"><span>Source disagreement</span><b>{f.spread.toFixed(1)} {config.unit}</b></div><p className="fine-print">Weighted standard deviation of source means. All sources are simulated.</p><div className="panel-chart"><div className="eyebrow">FORECAST EVOLUTION</div><Chart label="Seven-day forecast evolution at selected location" height={150} option={{grid:{top:16,left:30,right:10,bottom:25},xAxis:{type:'category',data:[24,48,72,96,120,144,168].map(h=>'+'+h),...gridAxis},yAxis:{type:'value',...gridAxis},series:[{type:'line',smooth:true,data:[24,48,72,96,120,144,168].map(h=>Number(forecast(loc.lat,loc.lng,h,variable).mean.toFixed(1))),symbolSize:4,lineStyle:{color:'#6ce5d3',width:2},itemStyle:{color:'#6ce5d3'},areaStyle:{color:'#6ce5d315'}}]}}/></div></>;
 let legendColors=config.colors,legendMin=variable==='temperature'?5:variable==='pressure'?985:0,legendMax=config.max,legendUnit=config.unit,legendTitle=LAYERS.find(l=>l.id===layer)?.label||config.label;
 if(layer==='risk'||layer==='weights'||layer==='agreement'){legendMin=0;legendMax=100;legendUnit='%';legendColors=layer==='agreement'?['#df9a61','#577b99','#66d4c4']:layer==='weights'?['#10232c','#27778b','#5adaca']:['#16334a','#536bc4','#ae7cbe','#eea07a'];}
 if(layer==='uncertainty'){legendMin=0;legendMax=variable==='rain'?100:15;legendColors=['#16334a','#536bc4','#ae7cbe','#eea07a'];legendTitle='P90 − P10';}
 return <TooltipProvider><main className="workbench"><header className="topbar"><a className="brand" href="/" aria-label="MausamSetu home"><Waypoints/><span>Mausam<span className="brand-accent">Setu</span><small>FORECAST INTELLIGENCE</small></span></a><Tabs value={tab} onValueChange={v=>setTab(v as Workspace)} className="navigation"><TabsList variant="line" aria-label="Workspaces">{NAV.map(n=><TabsTrigger key={n} value={n}>{n[0].toUpperCase()+n.slice(1)}</TabsTrigger>)}</TabsList></Tabs><div className="header-actions"><button className="demo-badge" onClick={()=>setInfo(true)}>DEMO DATA<Info size={11}/></button><IconButton label="About this run" onClick={()=>setInfo(true)}><Info size={17}/></IconButton></div></header><div className="contextbar"><div className="location-search"><Search size={16}/><Combobox items={LOCATIONS.map(l=>l.name)} value={LOCATIONS.some(l=>l.name===loc.name)?loc.name:null} onValueChange={(name:string|null)=>{const l=LOCATIONS.find(l=>l.name===name);if(l){setLoc(l);setTab('forecast');}}}><ComboboxInput aria-label="Search location" placeholder="Search a location in India" showTrigger={false}/><ComboboxContent><ComboboxEmpty>No matching locations. Select any point on the map.</ComboboxEmpty><ComboboxList>{(item:string)=><ComboboxItem key={item} value={item}>{item}<span className="search-state">{LOCATIONS.find(l=>l.name===item)?.state}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div><div className="run-context"><span>INITIALIZED <b>26 Sep 2026 · 00 UTC</b></span><span className="context-separator"/><span className="run-version">illustrative-gate-v1</span></div><div className="context-actions"><Picker label="Display timezone" value={tz} onChange={setTz} options={[{value:'UTC',label:'UTC'},{value:'IST',label:'IST'}]}/><IconButton label="Download forecast series CSV" onClick={exportSeries}><Download size={16}/></IconButton><IconButton label="Toggle fullscreen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>{});}}><Maximize size={15}/></IconButton></div></div>
 {tab==='forecast'?<SidebarProvider className="forecast-layout"><Sidebar collapsible="none" className="layer-panel"><SidebarContent>{layersContent}</SidebarContent></Sidebar><section className="map-area"><WeatherMap variable={variable} layer={layer} lead={lead} location={loc} onPick={pick} particles={particles} opacity={opacity} threshold={threshold} weightSource={weightSource} borders={borders}/><div className="map-heading"><span className="eyebrow">INDIA · {SOURCES.includes(layer as Source)?layer+' SOURCE':LAYERS.find(l=>l.id===layer)?.label.toUpperCase()}</span><h1>{config.label}<span>+{lead}h</span></h1><p>{variable==='rain'?'24-hour accumulation':variable==='wind'?'10 m wind speed':'Instantaneous field'} · synthetic field</p></div><button className="mobile-layers-button" onClick={()=>setMobileLayers(true)}><Layers size={16}/>Layers</button><button className="mobile-detail-button" onClick={()=>setMobilePanel(true)}><MapPin size={15}/>{loc.name}<b>{f.mean.toFixed(1)} {config.unit}</b><ChevronRight size={15}/></button><div className="map-caption">Click anywhere to inspect the forecast</div><div className="map-legend">{layer==='dominant'?<><span>Dominant source <b>+{lead}h</b></span><div className="categorical-legend">{SOURCES.map(s=><span key={s}><i style={{background:COLORS[s]}}/>{s}</span>)}</div></>:<><span>{layer==='weights'?weightSource+' contribution':layer==='blend'||SOURCES.includes(layer as Source)?config.label:legendTitle}<b>{legendUnit}</b></span><div className="color-ramp" style={{background:`linear-gradient(90deg,${legendColors.join(',')})`}}/><div className="legend-ticks">{Array.from({length:6},(_,i)=><span key={i}>{Math.round(legendMin+(legendMax-legendMin)*i/5)}</span>)}</div></>}</div></section><aside className="location-panel">{detail}</aside></SidebarProvider>:<div className="workspace-container">{tab==='compare'&&<><div className="compare-variable"><Picker label="Comparison variable" value={variable} onChange={v=>changeVariable(v as Variable)} options={Object.entries(VARIABLES).map(([value,c])=>({value,label:c.label}))}/></div><Compare variable={variable} lead={lead} location={loc} onPick={pick}/></>}{tab==='extremes'&&<Extremes lead={lead} onView={(l,v)=>openEvent(l,v,'forecast')} onCompare={(l,v)=>openEvent(l,v,'compare')} onExplain={(l,v)=>{openEvent(l,v,'forecast');setExplain(true);}}/>}{tab==='verification'&&<Verification rows={rows} loading={loading} error={dataError} onRetry={fetchRows}/>} {tab==='replay'&&<Replay rows={rows}/>} {tab==='operations'&&<Operations/>}</div>}
 {['forecast','compare','extremes'].includes(tab)&&<footer className="timeline"><button className="play-button" aria-label={playing?'Pause forecast animation':'Play forecast animation'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={18}/>:<Play size={18}/>}</button><div className="timeline-content"><div className="timeline-days">{Array.from({length:7},(_,i)=>{const d=new Date(Date.parse(INIT)+(i+1)*86400000);return <button key={i} className={Math.floor((lead-24)/24)===i?'current':''} onClick={()=>setLead((i+1)*24)}>{d.toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',timeZone:tz==='IST'?'Asia/Kolkata':'UTC'}).toUpperCase()}</button>;})}</div><Slider aria-label="Forecast lead hours" value={[lead]} min={24} max={168} step={6} onValueChange={x=>{setLead(x[0]);setPlaying(false);}}/><div className="timeline-meta"><span>{variable==='rain'?'ROLLING 24-HOUR ACCUMULATION':'VALID AT SELECTED TIME'} · {tz}</span><span>+{lead} HOURS · 6H STEPS</span></div></div><div className="time-label">{new Date(Date.parse(INIT)+lead*3600000).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:tz==='IST'?'Asia/Kolkata':'UTC'})}<small>{new Date(Date.parse(INIT)+lead*3600000).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:tz==='IST'?'Asia/Kolkata':'UTC'})} {tz}</small></div></footer>}
 <Dialog open={explain} onOpenChange={setExplain}><DialogContent className="explanation-dialog"><DialogHeader><div className="eyebrow">EXPLAINABLE BLENDING</div><DialogTitle>Why this blend?</DialogTitle><DialogDescription>{loc.name} · {config.label} · +{lead}h</DialogDescription></DialogHeader><div className="notice"><Info size={17}/><span>These weights come from an illustrative geographic and lead-time rule. No historical-skill or trained-AI claim is made.</span></div><div className="explain-summary"><div><span>Leading contribution</span><strong style={{color:COLORS[f.dominant]}}>{f.dominant} · {(Math.max(...f.weights)*100).toFixed(1)}%</strong></div><div><span>Source disagreement</span><strong>{f.spread.toFixed(1)} {config.unit}</strong></div></div><div className="explain-models">{SOURCES.map((s,i)=><div key={s}><span><i className="model-dot" style={{background:COLORS[s]}}/>{s}</span><b>{f.values[i].toFixed(1)} {config.unit}</b><span>× {(f.weights[i]*100).toFixed(1)}%</span></div>)}</div><div className="explain-method"><h3>How the result is calculated</h3><ol><li>Generate 21 synthetic distribution members for each source.</li><li>Apply context scores from location, variable, and forecast lead, then normalize the available-source scores with softmax.</li><li>Combine source distributions using these weights. Calculate the mean, P10–P90, and probability above {threshold} {config.unit} from the mixture.</li></ol><div className="formula">F<sub>blend</sub>(y) = Σ w<sub>m</sub> · F<sub>m</sub>(y)</div><p>Historical skill evidence: <b>not connected</b>. Weather regime classification: <b>not inferred from this fixture</b>. The backend includes calibration and trainable-gate modules for evaluated source archives.</p></div><Button variant="outline" onClick={()=>{setExplain(false);setTab('verification');}}>Inspect synthetic verification<ArrowUpRight size={15}/></Button></DialogContent></Dialog>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent><DialogHeader><DialogTitle>A transparent forecast workbench.</DialogTitle><DialogDescription>MausamSetu · SIH26081 implementation</DialogDescription></DialogHeader><p className="about-copy">The interactive map, comparisons, source weights, probabilities, and replay use a reproducible synthetic demonstration dataset. Model names identify illustrative sources, not connected feeds.</p><dl className="lineage"><dt>Run</dt><dd>{RUN}</dd><dt>Scientific status</dt><dd>Unvalidated demonstration</dd><dt>Wind</dt><dd>10 m speed; not gusts</dd><dt>Rainfall</dt><dd>Defined rolling 24-hour totals</dd><dt>Spatial interpretation</dt><dd>Selected point in a synthetic field</dd><dt>Boundaries</dt><dd>Natural Earth / geoBoundaries; illustrative only</dd></dl><p className="about-copy">Real operations require authorized NCUM/NEPS data, configured open-data inputs, historical calibration, institutional identity, and reviewed held-out evaluation. No public warning is issued.</p><Button variant="outline" onClick={()=>{setInfo(false);setTab('operations');}}>View operations<ArrowRightIcon/></Button></DialogContent></Dialog>
 <Sheet open={mobilePanel} onOpenChange={setMobilePanel}><SheetContent className="mobile-detail-sheet"><SheetTitle className="sr-only">Selected location forecast</SheetTitle><SheetDescription className="sr-only">Synthetic forecast values and source weights</SheetDescription><div className="location-panel">{detail}</div></SheetContent></Sheet><Sheet open={mobileLayers} onOpenChange={setMobileLayers}><SheetContent side="left" className="mobile-layer-sheet"><SheetTitle className="sr-only">Forecast layers</SheetTitle><SheetDescription className="sr-only">Choose variables and map layers</SheetDescription><SidebarProvider><div className="layer-panel">{layersContent}</div></SidebarProvider></SheetContent></Sheet></main></TooltipProvider>;
}
function ArrowRightIcon(){return <ChevronRight size={16}/>;}
